# Generated by Django 4.1.1 on 2022-11-12 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Peda', '0007_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
